branches:
  only:
  - master
  - "/^v.*$/"
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
language: python
matrix:
  include:
  - python: 3.6
  - python: 3.5
  - python: 2.7
  - os: osx
    language: generic
  - os: osx
    language: generic
    before_install:
    - brew update
    - brew install python3
    - virtualenv env -p python3
    - source env/bin/activate
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    install:
    - docker pull $DOCKER_IMAGE
    script:
    - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/.manylinux-install.sh
    after_success:
    - if [[ $TRAVIS_TAG ]]; then pip install twine && twine upload -u datamade.wheelbuilder
      -p $PYPIPASSWORD --skip-existing wheelhouse/*; fi
    - exit 0
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    install:
    - docker pull $DOCKER_IMAGE
    script:
    - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/.manylinux-install.sh
    after_success:
    - if [[ $TRAVIS_TAG ]]; then pip install twine && twine upload -u datamade.wheelbuilder
      -p $PYPIPASSWORD --skip-existing wheelhouse/*; fi
    - exit 0
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt
- cython --cplus doublemetaphone/*.pyx
- pip install -e .
script:
- pytest tests
deploy:
- provider: pypi
  skip_cleanup: true
  user: datamade.wheelbuilder
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = osx"
  distributions: bdist_wheel
  password: "$PYPIPASSWORD"
- provider: pypi
  skip_cleanup: true
  user: datamade.wheelbuilder
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
  distributions: sdist
  password: "$PYPIPASSWORD"
env:
  global:
  - secure: e619lcjt0Cw3YrgGRSWnVBJ/ZBvCrR6WCbM+7tDfmeeRLRT5uVvgjPFBbHEIL/2g3PFhBhX7UloewQWan8lPX67PhmBdqLw8tLJYqEa0lFK4vK+8gG8P7Qs9szr7Fkt30doz62MKBTMexbzVf1po6oxHYYbli/pNG1UGHuB9P9I8Y3JEj5UJbI+WZg4J8IReN8gJ+yApFgElZZCBFHGGux8iGkx0GP60sab1wMlHn38gpjJrnmAeneviUA70vsw7vVSFTrK5eewlAONu2EulsVTj8jscgsrOoXSrfEYto8CHBnjPyhthEmbsmcFuyhysy46+9+R6bc8Md7m9PcUmGxR+P74UCpxTX5rNKA6DaM90JnXue8X9F8O2C1SK44e7wrhCQ3XeHTKFPrZAMhczcrveaw2TILilIEWBmWPAu81HBMrGlAl66ANqjqBOwrXLIPJFlKaG4ySv4zyiZNGg814PRloKxttDVF2ic57VaJDyfUBQxpQa+OHXYUStjrLZUNi89VdUrOqce4McUi88QR8buI0+Jt7VvzX3JCpFa1P7jIMTdCf3OVCjVbXjekBhF/k2Z8L3NbZ2omScIIWlxvnwzvwaR11uKvCb/2A8yWC8gAKZYMfIEBbopojXZEtAwOzXl4FP2hGMyALGjgYhb+XYYOfkHKOiGpTa4BDz+QA=
